### ISSUE TITLE
Neustart des Koordinatensystems funktioniert nicht

### ISSUE THREAD

**Issue by dermondbaer** [g4rgoil/graphing_calculator#58]
Die restart-Methode produziert Errors, mit denen ich mich nicht näher befasst habe. Beim Initiieren der Klasse gebe ich nur den Master und die Größe vor, vielleicht hängt es damit zusammen.

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "D:\Bibliotheken\Paul\GitHub\graphing_calculator\geometry_tool\coordinate_system.py", line 29, in <lambda>
    self.__master.bind('<F5>', lambda event: self.restart())
  File "D:\Bibliotheken\Paul\GitHub\graphing_calculator\geometry_tool\coordinate_system.py", line 117, in restart
    self.__coordinate_system_canvas = CoordinateSystemCanvas(self, absolute_size)
TypeError: __init__() missing 1 required positional argument: 'axis_size'`

**Comment by pmehnert** [comment]
Du musst beim ersten inizieren alle argumente angeben!

**Comment by dermondbaer** [comment]
Die sind doch optional?! Aber oke mach ich dann halt ...

**Comment by pmehnert** [comment]
warte mal, hast du den Canvas selbst instanziert?

**Comment by dermondbaer** [comment]
nicht die Klasse CoordinatSystemCanvas, falls du das meinst

**Comment by pmehnert** [comment]
Mach mal woanders weiter, ich fix des.

**Comment by dermondbaer** [comment]
okay, ich bin dadurch eh nicht direkt eingeschränkt, weil ich del_figure() benutze

**Comment by pmehnert** [comment]
hä? del_figure und restart haben nicht den selben Zweck.

**Comment by dermondbaer** [comment]
Ja, man könnte aber auf die Idee kommen, damit alle Funktionen neu zeichnen zu lassen, statt sie einzeln zu löschen. Tue ich aber nicht, selbst wenn ich das wollte, wäre da ja noch clear_figures().

**Comment by pmehnert** [comment]
Dafuq?

**Comment by pmehnert** [comment]
Der Bug sollte gefixt sein.
